version: '3.5'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome01
      POSTGRES_DB: data_project1
    ports:
      - "5432:5432"
    volumes:
      - ./tablas.sql:/docker-entrypoint-initdb.d/tablas.sql

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app  

networks:
  postgres:
