version: '3.5'
 
services:
  postgres:
    container_name: postgres_container
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome01
      POSTGRES_DB: data_project1
    volumes:
       - ./tablas.sql:/docker-entrypoint-initdb.d/tablas.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


  python:
    container_name: python_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:


    
